config/routes.rb
Rails.application.routes.draw do
  
  
  get 'doctors/search'
  get 'patients/search'
  resources :activities
  resources :doctors
  resources :patients
  root 'welcomes#index'
  resources :users
  
  
  get 'cities/:state', to: 'application#cities'
  
  get 'welcomes/leaflet'
  devise_for :users ,only: :session , path: 'session',path_name: {sign_in:'login',sign_out: 'logout'}
  get   'users/change_passd/:id', to: 'users#change_passd'

  
  post  'patients/add_consulting', to: 'patients#add_consulting'
  get   'patients/:id/delete_consulting/:doctor_id' , to: 'patients#delete_consulting'

  
  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

   # conversations
   resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  get "*path", to: redirect("/404")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
    before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
        # how to get the number of unread messages for the current user
        # using mailboxer
        mailbox.inbox(:unread => true).count(:id)
      end
end

app/views/mailbox/_folder_view.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-header">
      <h1 style="color: #17a2b8" align="center">Messagerie</h1>
    </div>
    <hr>
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <!-- we'll configure this to compose new conversations later -->
    <%#= link_to "Composer", new_conversation_path , class: "btn btn-success" %>

    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
        <!-- individual conversations will show here -->
      </div>
    </div>
  </div>

</div>
  </div>
</div>

app/views/mailbox/_folders.html.erb
<ul class="nav flex-column">
  <!--<li class="<%#= active_page(:inbox) %>">
    <%#= link_to mailbox_inbox_path do  %>
      <span class="label label-danger pull-right"><%#=unread_messages_count%></span>
      <em class="fa fa-inbox fa-lg"></em>
      <span>Boîte de réception</span>
    <%# end %>
  </li>-->
  <%= link_to "Composer", new_conversation_path, class: "btn btn-success" %>
  <hr>
  <%= link_to "Boîte de réception", mailbox_inbox_path ,class:"btn btn-warning"%>
 <!-- <li class="<%#= active_page(:sent) %>">
    <%#= link_to mailbox_sent_path do %>

      <em class="fa fa-paper-plane-o fa-lg"></em>
      <span>Messages envoyés</span>
    <%# end %>
  </li>-->
  <hr>
  <%= link_to "Messages envoyés", mailbox_sent_path ,class:"btn btn-danger"%>

  <li class="<%= active_page(:trash) %>">
    <% link_to mailbox_trash_path do %>
      <em class="fa fa-trash-o fa-lg"></em>
      <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>