config/routes.rb
Rails.application.routes.draw do
  
  
  get 'doctors/search'
  get 'patients/search'
  resources :activities
  resources :doctors
  resources :patients
  root 'welcomes#index'
  resources :users
  
  
  get 'cities/:state', to: 'application#cities'
  
  get 'welcomes/leaflet'
  devise_for :users ,only: :session , path: 'session',path_name: {sign_in:'login',sign_out: 'logout'}
  get   'users/change_passd/:id', to: 'users#change_passd'

  
  post  'patients/add_consulting', to: 'patients#add_consulting'
  get   'patients/:id/delete_consulting/:doctor_id' , to: 'patients#delete_consulting'

  
  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

   # conversations
   resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  get "*path", to: redirect("/404")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord

    include PublicActivity::Model
    tracked owner: ->(controller, model) { controller && controller.current_user }

    has_many :consultings
    has_many :doctors, through: :consultings

    
    
has_attached_file :document
validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :add_consulting]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  def search
    @patien = Patient.where(['city LIKE ? AND sex LIKE ?', "%#{params[:city]}%","%#{params[:sex]}%"])
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @cont_sel = @patient.consultings
    @acha_pros = @patient.consultings
    @patient = Patient.find(params[:id])
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_consulting
    @pro = Consulting.new

    @doc = Doctor.find_by user_id: current_user

    @pro.doctor_id = @doc.id

    
    

    #@pros = Doctor.find(params[:doctor_id])
    @pro.doctor_name = @doc.name
    
    @pro.avis = params[:avis]
    @pro.patient_id = @patient.id
    @pro.patient_name = @patient.name
    if @pro.save!
      flash[:notice] = 'Avis enregistré avec succes.'
      redirect_to :action => :show, :id => params[:id]
    else
      flash[:error] = "Une erreur s'est produite."
      redirect_to :action => :show, :id => params[:id]
    end
  end

  def delete_consulting
    @pro = Consulting.find(params[:doctor_id])

   
    @pro.destroy
    respond_to do |format|
      format.html { redirect_to patient_url(params[:id]), notice: 'consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :date_of_birth, :sex, :address, :city, :country, :document_data, :document)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true, html: {class: "user"}) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" align="center">
    <%= form.label :Nom_et_Prenom %>
    <%= form.text_field :name ,class:"form-control form-control-lg col-4" %>
  </div>

  <div class="form-group" align="center">
    <%= form.label :Date_naissance %>
    <%= form.date_field :date_of_birth ,class:"form-control form-control-lg col-4"%>
  </div>

  <div class="form-group" align="center">
    <%= form.label :sexe %>
    <%= form.select :sex,options_for_select([["Homme","H"],["Femme","F"]]),{} ,class:"form-control form-control-lg col-4"%>
  </div>

  <div class="form-group" align="center">
    <%= form.label :address %>
    <%= form.text_area :address ,class:"form-control form-control-lg col-4"%>
  </div>

  <div class="form-group" align="center">
    <%= form.label :Wilayas %>
    <%= form.select :city, options_for_select(CS.states(:dz).map { |c| [c[1], c[0]] } ),{},class:"form-control form-control-lg col-4" %>
  </div>

  <div class="form-group" align="center">
    <%= form.label :pays %>
    <%= form.select :country, options_for_select(CS.countries.map { |c| [c[1], c[0]] } ),{},class:"form-control form-control-lg col-4" %>
  </div>

  <div class="form-group" align="center">
    <%= form.label :Dossier_médical %>
    <%= form.file_field :document ,class:"form-control form-control-lg col-4"%>
  </div>
  <hr>
  <div class="form-group" align="center">
    <%= form.submit "Sauvegarder Patient" , class:"btn btn-primary btn-user btn-block col-4" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="card">
    <div class="card-body">
      <div class="card-header ">

        <h1 style="color: #17a2b8" align="center"> Modification de Patient <br> <%= @patient.name%> </h1>
      </div>
      <div class="panel-body">
      <br>
<%= link_to '', @patient ,class:"fas fa-tv fa-2x  btn-success btn-lg" %> 
<%#= link_to '', patients_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%>
<hr>
<%= render 'form', patient: @patient %>

</div>
     <div>
</div>

app/views/patients/index.html.erb
<!-- Page Heading -->

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-2 text-gray-800">Patients</h1>

      <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-info-circle"> Total</i>
                    </span>
      <span class="text"><%= @patients.count%></span>
    </a>

    <a href="<%= new_patient_path %>" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
      <span class="text">Nouveau patient</span>
    </a>
  </div>
  
 

<!-- Content Row -->

          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-9 col-lg-8">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Patients</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  
                  <table class="table table-bordered table-responsive" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Nom Prenom</th>
      <th>Date naissance</th>
      <th>Sexe</th>
      <th>Address</th>
      <th>Wilaya</th>
      <th>Pays</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.sex %></td>
        <td><%= patient.address %></td>
        <td><%= patient.city %></td>
        <td><%= patient.country %></td>
        <td><%= link_to '', patient ,class:"fas fa-tv fa-2x  btn-success btn-lg"%></td>
        <td><%= link_to '', edit_patient_path(patient),class:"fas fa-edit fa-2x btn-primary btn-lg" %></td>
        <td><%= link_to '', patient, method: :delete, data: { confirm: 'Are you sure?' } ,class:"fas fa-trash fa-2x btn-danger btn-lg" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

                </div>
              </div>
            </div>

            <!-- Pie Chart -->
            <div class="col-xl-3 col-lg-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Statistiques</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <%= pie_chart Patient.group(:city).count %>
                </div>
              </div>
            </div>
          </div>

app/views/patients/new.html.erb
<div class="card">
    <div class="card-body">
      <div class="card-header ">

        <h1 style="color: #17a2b8" align="center"> Nouveau Patient</h1>
      </div>
      <div class="panel-body">
      <br>
<%#= link_to '', patients_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%>

<%= render 'form', patient: @patient %>

 </div>
  </div>
</div>

app/views/patients/search.html.erb
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Recherche Avancée</h1>

<br>
<div class="col-xl-12 col-md-6 mb-4 res">
  <!-- Collapsable Card Example -->
  <div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
      <h6 class="m-0 font-weight-bold text-primary">Chercher Patients</h6>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col-xl-12 col-md-6 mb-4 res">

            <%= form_tag patients_search_path, method: :get do %>
              <div class="row">

                <div class="col-xl-4 col-md-6 mb-4 align-self-start"  >
                  <%#= label_tag 'Wilayas' , nil ,class: 'mr-sm-2' %>
                  <%#= select_tag :city ,options_for_select([["Setif","setif"],["Alger","alger"],["Oran","oran"]] ),{prompt: "Select Wilaya",class:"form-control form-control"}%>
                  <%= select_tag :city, options_for_select(CS.states(:dz).map { |c| [c[1], c[0]] } ),{prompt: "Select Wilaya",class:"form-control "} %>

                </div>

                <div class="col-xl-4 col-md-6 mb-4 align-self-center">
                  <%#= label_tag 'Sexe' , nil ,class: 'mr-sm-2' %>
                  <%= select_tag :sex, options_for_select(Patient.all.map{|u| [u.sex ] }.uniq),{prompt: "sex",class:"form-control form-control"} %>
                </div>

                
        
                <div class="col-xl-4 col-md-6 mb-4 align-self-end">
                  <%= submit_tag "Chercher Patients ",class:"btn btn-md btn-info" %>
                </div>
            <% end %>
            </div>
          </div>
        </div>
       


        
      </div>
    </div>
  </div>

  <div class="row" id="table_search" style="padding: 10px">
     
  <% @patien.each do |pat| %>
   <div class="col-xl-4 col-md-6 mb-4">
    <div class="card text-center border-info shadow h-100 py-2">
      <div class="card border-info shadow h-100 py-2">
      <div class="card-header">
        <strong style="color: #17a2b8" align="center">Patient: <%= pat.name %></strong>
      </div>

          <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Wilaya</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= pat.city %></div>
                  <hr>
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Sexe</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= pat.sex %></div>
                  <hr>
                </div>
            </div>

        <br>
        <%= link_to 'Voir', pat ,class:"btn btn-info"%>
      </div>
            </div>
</div>
    </div>
  <% end %>

  <br>

app/views/patients/show.html.erb
<div class="card">

    <div class="card-body">
    <div class="card-header">
     <h1 style="color: #17a2b8" align="center">Le patient <br> <%= @patient.name%> </h1>
     </div>
      <br>
          <%= link_to '', edit_patient_path(@patient) ,class:"fas fa-tv fa-2x  btn-primary btn-lg"%> |
          <%#= link_to '', patients_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%> 
          <a class="fa fa-medkit fa-2x  btn-info btn-lg" data-toggle="modal" href="#betaModal"></a>
                  <div id="betaModal" class="modal fade" role="dialog">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                        <h4 class="modal-title">Ajouter Consultation</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                          

                    <%= form_tag(patients_add_consulting_url, {:method => :post}) do %>
                        <%= hidden_field_tag :id, @patient.id %>
                        <!--
                        <div class="form-group">
                          <strong>Médecins:</strong>
                          <%#= select_tag :doctor_id, options_for_select(Doctor.all_except(@cont_sel.map(&:doctor_id)).map { |s| [s.name, s.id] }.compact), { prompt: "select doctor", class: 'form-control',:required => true} %>
                        </div>    -->
                        <div class="form-group">
                          <strong>Avis:</strong>
                          <%= text_area_tag :avis,nil,{class:"form-control" ,placeholder:"Tape avis in here...",:required => true}%>
                        </div>
                        <div class="form-group">
                          <br>
                          <%= submit_tag 'Ajouter', class: 'btn btn-success' %>
                        </div>
                    <% end %>
                  
                        </div>
                        <!-- Modal footer -->
                  <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                  </div>
                      </div>
                    </div>
                  </div>

<br>
<hr>
<br>

 <!-- Collapsable Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                  <h6 class="m-0 font-weight-bold text-primary">Fiche Technique Patient</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample">
                  <div class="card-body">
<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Nom Prenom</i>
                    </span>
                    <span class="text"><%= @patient.name %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Date naissance</i>
                    </span>
                    <span class="text"><%= @patient.date_of_birth %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Sexe</i>
                    </span>
                    <span class="text"><%= @patient.sex %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Address</i>
                    </span>
                    <span class="text"><%= @patient.address %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Wilaya</i>
                    </span>
                    <span class="text"><%= @patient.city %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Pays</i>
                    </span>
                    <span class="text"><%= @patient.country %></span>
                  </a>
            </div>
          </div>
        </div>
 




                  <!-- Collapsable Card Example -->
                  <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample1">
                      <h6 class="m-0 font-weight-bold text-primary">Doussier Medical</h6>
                    </a>
                    <!-- Card Content - Collapse -->
                    <div class="collapse show" id="collapseCardExample1">
                      <div class="card-body">
                        <%if @patient.document_file_name != nil %>
                          <iframe src="<%= @patient.document %>" width="100%" height="1000"></iframe>
                        <%else%>
                          <p class="text-center"><font size="4" >There is no file attached to this patient</font></p>
                        <%end%>
                      </div>
                    </div>
                  </div>
        
     
   
  
  
 
                  <!-- Collapsable Card Example -->
                  <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">
                      <h6 class="m-0 font-weight-bold text-primary">Consultations</h6>
                    </a>
                    <!-- Card Content - Collapse -->
                    <div class="collapse show" id="collapseCardExample2">
                      <div class="card-body">      
                        <table class="table table-bordered table-responsive" id="dataTable" width="100%" cellspacing="0">
                          <thead>
                          <tr>
                            <th>Médecin</th>
                            <th>Spécialité</th>
                            <th>Wilaya</th>
                            <th>Address</th>
                            <th>Patient</th>
                            
                            <th>Avis</th>
                            <th>Show</th> 
                            <th>Delete</th>    
                          </tr>
                          </thead>
                          <tbody>
                          <% @acha_pros.each { |s| %>
                              <tr>
                                <td><%= s.doctor_name %></td>
                                <td><%= s.doctor.specialist %></td>
                                <td><%= s.doctor.city %></td>
                                <td><%= s.doctor.address %></td>
                                <td><%= s.patient_name %></td>
                                
                                <td><%= s.avis %></td>
                                <td><%= link_to '', s.doctor ,class:"fas fa-tv fa-2x  btn-success btn-lg"%></td>
                                <td><%= link_to '', "/patients/#{params[:id]}/delete_consulting/#{s.id};", data: { confirm: 'Are you sure?' } ,class:"fas fa-trash fa-2x btn-danger btn-lg"%></td>
                                

                              </tr>                                 
                          <% } %>
                          </tbody>
                        </table>
                      </div>
                    </div>                    
                 </div>






                      </div>
                    </div>
                  </div>