config/routes.rb
Rails.application.routes.draw do
  
  
  get 'doctors/search'
  get 'patients/search'
  resources :activities
  resources :doctors
  resources :patients
  root 'welcomes#index'
  resources :users
  
  
  get 'cities/:state', to: 'application#cities'
  
  get 'welcomes/leaflet'
  devise_for :users ,only: :session , path: 'session',path_name: {sign_in:'login',sign_out: 'logout'}
  get   'users/change_passd/:id', to: 'users#change_passd'

  
  post  'patients/add_consulting', to: 'patients#add_consulting'
  get   'patients/:id/delete_consulting/:doctor_id' , to: 'patients#delete_consulting'

  
  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

   # conversations
   resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  get "*path", to: redirect("/404")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord

    include PublicActivity::Model
    tracked owner: ->(controller, model) { controller && controller.current_user }

    has_many :consultings
    has_many :patients, through: :consultings

    belongs_to :user

    scope :all_except, ->(s) { where.not(id: s) }
    
    after_initialize :set_defaults 

    geocoded_by :address
    after_validation :geocode

    validates_presence_of :name ,:city

    has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    def set_defaults
        self.country ||= "algerie"
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
      @doctors = Doctor.all
  end

  def search
    @doctos = Doctor.where(['city LIKE ? AND specialist LIKE ?', "%#{params[:city]}%","%#{params[:specialist]}%"])
  end


  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @cont_sel = @doctor.consultings
    @acha_pros = @doctor.consultings
    @doctor = Doctor.find(params[:id])
  end

  

  # GET /doctors/new
  def new
    if can? :update, @users
    @doctor = Doctor.new
  else
      
    redirect_to :root
    flash[:alert] = "Vous n'avez pas les deroits a acceder ces informations."
  end
  end

  # GET /doctors/1/edit
  def edit
    
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :date_of_birth, :sex, :specialist, :address, :city, :country, :avatar,:num_ordre,:sous_spesialist)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<div class="card">
    <div class="card-body">
      <div class="card-header ">

        <h1 style="color: #17a2b8" align="center"> Modification de Médecin <br> <%= @doctor.name%> </h1>
      </div>
      <div class="panel-body">
      <br>
      <%= link_to '', @doctor ,class:"fas fa-tv fa-2x  btn-success btn-lg" %> 
<%#= link_to '', doctors_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%>

<hr>

<%= render 'form', doctor: @doctor %>
</div>
     <div>
</div>

app/views/doctors/index.html.erb
<!-- Page Heading -->

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-2 text-gray-800">Médecins</h1>

      <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-info-circle"> Total</i>
                    </span>
      <span class="text"><%= @doctors.count%></span>
    </a>

  <!--  <a href="<%#= new_doctor_path %>" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
      <span class="text">Nouveau Médecin</span>
    </a>  -->
  </div> 
 
 

<!-- Content Row -->

          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-9 col-lg-8">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Médecins</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  
                  <table class="table table-bordered table-responsive" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Nom Prenom</th>
      <th>Date naissance</th>
      <th>Sexe</th>
      <th>Spécialité</th>
      <th>Address</th>
      <th>Wilaya</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.date_of_birth %></td>
        <td><%= doctor.sex %></td>
        <td><%= doctor.specialist %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.city %></td>
        
        <td><%= link_to '', doctor ,class:"fas fa-tv fa-2x  btn-success btn-lg"%></td>
        <td><%= link_to '', edit_doctor_path(doctor),class:"fas fa-edit fa-2x btn-primary btn-lg" %></td>
        <td><%= link_to '', doctor, method: :delete, data: { confirm: 'Are you sure?' } ,class:"fas fa-trash fa-2x btn-danger btn-lg"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

 </div>
              </div>
            </div>

            <!-- Pie Chart -->
            <div class="col-xl-3 col-lg-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Statistiques</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <%= pie_chart Doctor.group(:city).count, donut: true %>
                  <hr>
                  <%= bar_chart Doctor.group(:specialist).count %>
                </div>
              </div>
            </div>
          </div>

app/views/doctors/new.html.erb
<div class="card">
    <div class="card-body">
      <div class="card-header ">

        <h1 style="color: #17a2b8" align="center"> Nouveau Médecin</h1>
      </div>
      <div class="panel-body">
      <br>

<%#= link_to '', doctors_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%>

<%= render 'form', doctor: @doctor %>

</div>
  </div>
</div>

app/views/doctors/search.html.erb
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Recherche Avancée</h1>

<br>
<div class="col-xl-12 col-md-6 mb-4 res">
  <!-- Collapsable Card Example -->
  <div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
      <h6 class="m-0 font-weight-bold text-primary">Chercher Médecins</h6>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col-xl-12 col-md-6 mb-4 res">

            <%= form_tag doctors_search_path , method: :get do %>
              <div class="row">

                <div class="col-xl-4 col-md-6 mb-4 align-self-start"  >
                  <%#= label_tag 'Wilayas' , nil ,class: 'mr-sm-2' %>
                  <%#= select_tag :city ,options_for_select([["Setif","setif"],["Alger","alger"],["Oran","oran"]] ),{prompt: "Select Wilaya",class:"form-control "}%>
                  <%= select_tag :city, options_for_select(CS.states(:dz).map { |c| [c[1], c[0]] } ),{prompt: "Select Wilaya",class:"form-control "} %>
                </div>
                
                <div class="col-xl-4 col-md-6 mb-4 align-self-center">
                  <%#= label_tag :Spécialité, nil ,class: 'mr-sm-2'%>
                  <%#= select_tag :specialist, options_for_select(Doctor.all.map{|u| [u.specialist ] }.uniq),{prompt: "Spécialité",class:"form-control form-control"} %>
                  <%= select_tag :specialist,options_for_select([["Allergologie","Allergologie"],["Biologie bactériologie","Biologie bactériologie"],
    ["Biologie Biochimie","Biologie Biochimie"],["Biologie chimie ","Biologie chimie "],["Biologie virologie","Biologie virologie"],["Cardiologie","Cardiologie"],
    ["Chirurgie dentaire","Chirurgie dentaire"],["Chirurgie esthétique ","Chirurgie esthétique "],["Chirurgie infantile","Chirurgie infantile"],["Chirurgie maxillo-faciale","Chirurgie maxillo-faciale"],
    ["Chirurgie Orthopédie","Chirurgie Orthopédie"],["Chirurgie générale ","Chirurgie générale "],["Dermatologie","Dermatologie"],["Diabétologie","Diabétologie"],
    ["Endocrinologie","Endocrinologie"],["Epidémiologie","Epidémiologie"],["Gastrologie","Gastrologie"],["Gynécologie obstétrique","Gynécologie obstétrique"],
    ["Hématologie","Hématologie"],["Immunologie","Immunologie"],["Maladies Infectieuses","Maladies Infectieuses"],["Médecine de sport","Médecine de sport"],
    ["Médecine de travail","Médecine de travail"],["Médecine interne","Médecine interne"],["Médecine légale","Médecine légale"],["Néphrologie","Néphrologie"],
    ["Neurochirurgie","Neurochirurgie"],["Neurologie","Neurologie"],["O.R.L","O.R.L"],["Oncologie","Oncologie"],
    ["Ophtalmologie","Ophtalmologie"],["Pédiatrie","Pédiatrie"],["Pneumo-phtisiologie","Pneumo-phtisiologie"],["Psychologie","Psychologie"],
    ["Radiologie","Radiologie"],["Rééducation fonctionnelle","Rééducation fonctionnelle"],["Rhumatologie","Rhumatologie"],["Sénologie","Sénologie"],
    ["Urologie","Urologie"]
    ]),{prompt: "Spécialité",class:"form-control form-control"} %>
                </div>
                
                <div class="col-xl-4 col-md-6 mb-4 align-self-end">
                  <%= submit_tag "Chercher Médecins ",class:"btn btn-primary" %>
                </div>
                
            <% end %>
           </div>
          </div>
        </div>
        


        
      </div>
    </div>
  </div>

  <div class="row" id="table_search" style="padding: 10px">

  <% @doctos.each do |doc| %>
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card text-center border-info shadow h-100 py-2">
      <div class="card border-info shadow h-100 py-2">
      <div class="card-header">
        <strong style="color: #17a2b8" align="center">Dr. <%= doc.name %></strong>
      </div>

          <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Wilaya</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= doc.city %></div>
                  <hr>
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">specialist</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= doc.specialist %></div>
                  <hr>
                </div>
            </div>
        <br>
        <%= link_to 'Voir', doc ,class:"btn btn-info"%>
      </div>
            </div>
</div>
    </div>
  <% end %>

  <br>

app/views/doctors/show.html.erb
<style>
.purr {
  position: fixed;
  top: 30px;
  right: 100px;
  width: 250px;
  padding: 20px;
  background-color: #FCC;
  border: solid 2px #C66;
  &:first-letter { text-transform: uppercase; }
}
</style>
<div class="card">

    <div class="card-body">
    <div class="card-header">
     <h1 style="color: #17a2b8" align="center">Le médecin <br> <%= @doctor.name%> </h1>
     </div>
      <br>
<%= link_to '', edit_doctor_path(@doctor),class:"fas fa-tv fa-2x  btn-primary btn-lg" %> 
<%#= link_to '', doctors_path ,class:"fas fa-arrow-left fa-2x  btn-warning btn-lg"%>

<br>
      <hr>


    <br>

<!-- Content Row -->

          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-9 col-lg-8">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Fiche Technique Médecin</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                <div class="row">
                <div class="col">
                
<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Nom Prenom</i>
                    </span>
                    <span class="text"><%= best_in_place @doctor, :name  %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Date naissance</i>
                    </span>
                    <span class="text"><%= @doctor.date_of_birth %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Sexe</i>
                    </span>
                    <span class="text"><%= best_in_place @doctor, :sex %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Spécialité</i>
                    </span>
                    <span class="text"><%= best_in_place @doctor, :specialist,:as => :select, :collection => [["Allergologie","Allergologie"],["Biologie bactériologie","Biologie bactériologie"],
    ["Biologie Biochimie","Biologie Biochimie"],["Biologie chimie ","Biologie chimie "],["Biologie virologie","Biologie virologie"],["Cardiologie","Cardiologie"],
    ["Chirurgie dentaire","Chirurgie dentaire"],["Chirurgie esthétique ","Chirurgie esthétique "],["Chirurgie infantile","Chirurgie infantile"],["Chirurgie maxillo-faciale","Chirurgie maxillo-faciale"],
    ["Chirurgie Orthopédie","Chirurgie Orthopédie"],["Chirurgie générale ","Chirurgie générale "],["Dermatologie","Dermatologie"],["Diabétologie","Diabétologie"],
    ["Endocrinologie","Endocrinologie"],["Epidémiologie","Epidémiologie"],["Gastrologie","Gastrologie"],["Gynécologie obstétrique","Gynécologie obstétrique"],
    ["Hématologie","Hématologie"],["Immunologie","Immunologie"],["Maladies Infectieuses","Maladies Infectieuses"],["Médecine de sport","Médecine de sport"],
    ["Médecine de travail","Médecine de travail"],["Médecine interne","Médecine interne"],["Médecine légale","Médecine légale"],["Néphrologie","Néphrologie"],
    ["Neurochirurgie","Neurochirurgie"],["Neurologie","Neurologie"],["O.R.L","O.R.L"],["Oncologie","Oncologie"],
    ["Ophtalmologie","Ophtalmologie"],["Pédiatrie","Pédiatrie"],["Pneumo-phtisiologie","Pneumo-phtisiologie"],["Psychologie","Psychologie"],
    ["Radiologie","Radiologie"],["Rééducation fonctionnelle","Rééducation fonctionnelle"],["Rhumatologie","Rhumatologie"],["Sénologie","Sénologie"],
    ["Urologie","Urologie"]] %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Sous Spécialité</i>
                    </span>
                    <span class="text"><%= @doctor.sous_spesialist %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Numero d'ordre</i>
                    </span>
                    <span class="text"><%= @doctor.num_ordre %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Address</i>
                    </span>
                    <span class="text"><%= best_in_place @doctor, :address,:as => :textarea %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Wilaya</i>
                    </span>
                    <span class="text"><%= @doctor.city %></span>
                  </a>

<div class="my-2"></div>
                  <a href="#" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                      <i>Pays</i>
                    </span>
                    <span class="text"><%= @doctor.country %></span>
                  </a>
</div>

         <div class="col">
             <%= image_tag @doctor.avatar.url(:medium),height: '100%', width: '100%',class: "img-thumbnail" %>
         </div>
</div>
</div>
</div>


<!-- Collapsable Card Example -->
                  <div class="card shadow mb-4">
                    <!-- Card Header - Accordion -->
                    <a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">
                      <h6 class="m-0 font-weight-bold text-primary">Consultations</h6>
                    </a>
                    <!-- Card Content - Collapse -->
                    <div class="collapse show" id="collapseCardExample2">
                      <div class="card-body">      
                        <table class="table table-bordered table-responsive" id="dataTable" width="100%" cellspacing="0">
                          <thead>
                          <tr>
                            <th>Patient</th>
                            <th>Wilaya</th>
                            <th>Address</th>
                            <th>Avis</th>
                            <th>Voir</th> 
                          </tr>
                          </thead>
                          <tbody>
                          <% @acha_pros.each { |s| %>
                              <tr>
                                <td><%= s.patient_name %></td>
                                <td><%= s.patient.city %></td>
                                <td><%= s.patient.address %></td>
                                <td><%= s.avis %></td>
                                <td><%= link_to '', s.patient ,class:"fas fa-tv fa-2x  btn-success btn-lg"%></td>
                                

                              </tr>                                 
                          <% } %>
                          </tbody>
                        </table>
                      </div>
                    </div>                    
                 </div>






          
        </div>
        </div>


<script>
$(document).ready(function() {
  /* Activating Best In Place */
  jQuery(".best_in_place").best_in_place();
});
</script>